// Generated by CoffeeScript 1.3.2-pre
(function() {
  var ChatController;

  ChatController = require('../../lib/controllers/chat_controller');

  describe('ChatController', function() {
    var app, chat, chatController, reqStub, resStub;
    chat = {};
    app = {};
    chatController = null;
    reqStub = Object.create(null);
    resStub = Object.create(null);
    beforeEach(function() {
      app.send = sinon.stub();
      return chatController = new ChatController(app);
    });
    it('just works', function() {
      return expect(true).to.be(true);
    });
    return describe('rendering the ChatView', function() {
      return it('creates HTML for the ChatView', function() {
        var firstArg;
        chatController.renderChatView(reqStub, resStub);
        firstArg = app.send.args[0][0];
        expect(firstArg).to.match(/\#chat/);
        return expect(app.send).to.have.been.called();
      });
    });
  });

}).call(this);
